### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by codenooobb** [ericz99/nike-monitor#3]
This doesnt seem to work, dont know if its just not finished or im doing something wrong but it doesnt monitor anything. I had this going for 2 days and its said the same thing. https://gyazo.com/7fb94faa434c571b7a99a9617f9cdbd8

**Comment by ericz99** [comment]
Bud, did you read my readme? Rushing me will result in a bad performance.

**Comment by codenooobb** [comment]
I seen the check marks and thought it was ready to do those things. Sorry, good luck
